# Default values for storage-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  # configmaps
  logLevel: "ERROR"
  springProfilesActive: "gcp"
  defaultDataCountry: "US"
  storageServiceAccountEmail: "storage@service.local"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  crsConverterHost: "http://crs-conversion"
  legalHost: "http://legal"
  redisGroupHost: "redis-group-master"
  redisStorageHost: "redis-storage-master"
  googleAudiences: ""
  opaEnabled: true
  opaEndpoint: "http://opa"
  storageHost: "http://storage"
  defaultLegalTag: "default-data-tag"
  dataPartitionId: ""
  # deployments
  requestsCpu: "0.25"
  requestsMemory: "1024M"
  limitsCpu: "1"
  limitsMemory: "3G"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "storage"
conf:
  appName: "storage"
  keycloakSecretName: "storage-keycloak-secret"
  minioSecretName: "storage-minio-secret"
  postgresSecretName: "storage-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  bootstrapSecretName: "datafier-secret"
  replicas: 3
  onPremEnabled: false
  bootstrapEnabled: false
  domain: ""
