# Default values for storage-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# common
data:
  requestsCpu: "0.25"
  requestsMemory: "2048M"
  limitsCpu: "1"
  limitsMemory: "3G"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "storage"
conf:
  appName: "storage"
  configmap: "storage-config"
  keycloakSecretName: "storage-keycloak-secret"
  minioSecretName: "storage-minio-secret"
  postgresSecretName: "storage-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  bootstrapSecretName: "datafier-secret"
  replicas: 3
  onPremEnabled: false
  bootstrapEnabled: false
  domain: ""
