# Default values for storage-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requests_cpu: "0.25"
  requests_memory: "2048M"
  limits_cpu: "1"
  limits_memory: "3G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "storage-config"
  app_name: "storage"
  replicas: 3
