variables:
  # refactor is required
  OSDU_GCP_SERVICE: storage
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_DEFAULT_DATA_COUNTRY: US
  OSDU_GCP_TEST_SUBDIR: testing/$OSDU_GCP_SERVICE-test-$OSDU_GCP_VENDOR
  # --- osdu specific variables for GKE ---
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: >
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.redis_group_host=$REDIS_GROUP_HOST
    --set data.redis_storage_host=$REDIS_STORAGE_HOST
    --set data.storage_service_account_email=workload-storage-gcp@$OSDU_GCP_PROJECT.iam.gserviceaccount.com
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.redis_group_host=$REDIS_GROUP_HOST
    --set data.redis_storage_host=$REDIS_STORAGE_HOST
    --set data.storage_service_account_email=workload-storage-gcp@$OSDU_GCP_PROJECT.iam.gserviceaccount.com
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: >
    --set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-$OSDU_GCP_SERVICE:$CI_COMMIT_SHORT_SHA
    --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s
  OSDU_GCP_HELM_CONFIG_SERVICE: storage-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: storage-deploy
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
