variables:
  OSDU_GCP_SERVICE: storage
  OSDU_GCP_VENDOR: gcp
  NO_DATA_ACCESS_TESTER: $OSDU_GCP_NO_DATA_ACCESS_TESTER

osdu-gcp-anthos-test:
  variables:
    OSDU_GCP_VENDOR: anthos
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_ID: storage-no-access-tester
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET: $OSDU_ANTHOS_STORAGE_NO_ACCESS_CLIENT_SECRET
