# Service Config
image: __CONTAINER__
imagePullPolicy: Always
service:
  type: ClusterIP
  port: 8080
  apiPath: /api/storage/v2/
  readinessType: exec
  readinessProbeHttpPath: /api/storage/v2/health
  startupProbeHttpPath: /api/storage/v2/health
serviceParameters:
  - objectName: "/osdu/{{ .Values.global.resourcePrefix }}/primary-region"
    objectType: "ssmparameter"
    objectAlias: primary-region
  - objectName: "/osdu/{{ .Values.global.resourcePrefix }}/storage/storage-sns-topic-arn"
    objectType: "ssmparameter"
    objectAlias: storage-sns-topic-arn
  - objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis/redisauthtoken"
    objectType: "secretsmanager"
    objectAlias: "CACHE_CLUSTER_KEY"
  - objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis-core/end-point"
    objectType: "ssmparameter"
    objectAlias: "CACHE_CLUSTER_ENDPOINT"
  - objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis-core/end-point-port"
    objectType: "ssmparameter"
    objectAlias: "CACHE_CLUSTER_PORT"   
  - objectName: "/osdu/{{ .Values.global.resourcePrefix }}/service-principal-user"
    objectType: "ssmparameter"
    objectAlias: "SERVICE_PRINCIPAL"    
environmentVariables:
  - name: APPLICATION_PORT
    value: "{{ .Values.service.port }}"
  - name: AWS_REGION
    value: "{{ .Values.global.region }}"
  - name: ENVIRONMENT
    value: "{{ .Values.global.resourcePrefix }}"
  - name: JAVA_OPTS
    value: "-Xms50M -Xmx900M"
  - name: LOG_LEVEL
    value: "{{ default `INFO` .Values.global.logLevel }}"
  - name: SSM_ENABLED
    value: "True"
  - name: SSL_ENABLED
    value: "false"
  - name: ENTITLEMENTS_BASE_URL
    value: "http://os-entitlements:8080"
  - name: PARTITION_BASE_URL
    value: http://os-partition:8080
  - name: LEGALTAG_BASE_URL
    value: http://os-legal:8080
  - name: POLICY_BASE_URL
    value: http://os-policy:8080
  - name: CRS_CONVERSION_BASE_URL
    value: http://os-crs-conversion:8080
  - name: OPA_URL
    value: http://opa-agent
  - name: OPA_ENABLED
    value: "true"
  - name: PARAMETER_MOUNT_PATH
    value: "/mnt/params"

# Resource Config
maxConnections: 200
replicaCount: 1
resources:
  limits:
    memory: 900M
  requests:
    cpu: 500m
    memory: 900M
autoscaling:
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 90
  coolDownPeriod: 120
  ServiceRequestCountThreshold: 35
  ServiceRequestDurationAverage: 500

# Security Config
serviceAccountRole: arn:aws:iam::{{ .Values.global.accountID }}:role/osdu-{{ .Values.global.resourcePrefix }}-{{ .Values.global.region }}-{{ include "common.name" . }}
cors:
  maxAge: "60m"
  allowCredentials: true
  allowMethods: 
    - POST
    - GET
    - PUT
    - PATCH
    - DELETE
  allowHeaders:
    - Authorization
    - Data-Partition-Id
    - Correlation-Id
    - Content-Type
securityContext: 
  runAsUser: 10001
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
podSecurityContext: 
  fsGroup: 1337
  seccompProfile:
    type: RuntimeDefault

allowedPrincipals:
  - cluster.local/ns/istio-system/sa/istio-ingressgateway
  - cluster.local/ns/{{ .Release.Namespace }}/sa/compliance-queue
  - cluster.local/ns/{{ .Release.Namespace }}/sa/indexer-queue
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-crs-conversion
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-dataset
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-file
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-file-dms
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-indexer
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-unit
  - cluster.local/ns/os-timeseries-dms/sa/os-timeseries-dms
  - cluster.local/ns/aws-binary-dms/sa/binary-dms
  - cluster.local/ns/osdu-airflow/sa/airflow-dag-upload
  - cluster.local/ns/osdu-airflow/sa/airflow-worker
  - cluster.local/ns/osdu-ingest/sa/os-data-workflow
  - cluster.local/ns/osdu-ingest/sa/os-ingestion-workflow
  - cluster.local/ns/osdu-seismic-ddms/sa/os-seismic-store
  - cluster.local/ns/osdu-well-delivery/sa/os-welldelivery
  - cluster.local/ns/osdu-wellbore-ddms/sa/os-wellbore-ddms
