{{- if .Values.rosa }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "nonroot-scc-redis-%s" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
subjects:
  - kind: ServiceAccount
    name: {{ printf "redis-%s" .Values.data.serviceAccountName | quote }}
    namespace: {{ .Release.Namespace | quote }}

{{- end }}

