apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  DEPLOYMENT_ENVIRONMENT: "{{ .Values.data.deployEnv }}"

  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  server.servlet.context-path: "{{ .Values.data.contextPath }}"
  server.port: "{{ .Values.data.serverPort }}"
  spring.main.allow-bean-definition-overriding: "{{ .Values.data.beanDefOverriding }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"
    
  cache.expiration: "{{ .Values.data.cacheExpiration }}"
  cache.maxSize: "{{ .Values.data.cahceMaxSize }}"
  ibm.health-check-uri: "{{ .Values.data.healthCheckUri }}"
  logging.level.org.opengroup.osdu: "{{ .Values.data.loggingLevelOsdu }}"
  logging.level.org.springframework.web: "{{ .Values.data.loggingLevelSpring }}"

  AUTHORIZE_API: "http://{{ .Release.Name }}-ibm-entitlement-deploy:8080/api/entitlements/v2"
  LEGALTAG_API: "http://{{ .Release.Name }}-ibm-legal-deploy:8080/api/legal/v1"
  PARTITION_API: "http://{{ .Release.Name }}-ibm-partition-deploy:8080/api/partition/v1"

  #db
  ibm.db.url: "http://{{ .Release.Name }}-couchdb:5984"
  ibm.db.user: "{{ .Values.data.dbUser }}"
  ibm.db.password: "{{ .Values.data.dbPassw }}"
  ibm.env.prefix: "{{ .Values.data.envPrefix }}"
  ibm.env.prefix_project: "{{ .Values.data.envPrefixProject }}"

  #tenant validation
  partition.keycloak.url: "{{ .Values.data.pKCEndPointHost }}"
  partition.keycloak.client_id: "{{ .Values.data.pKCClientId }}"
  partition.keycloak.client_secert: "{{ .Values.data.pKCClientSecret }}"
  partition.keycloak.grant_type: "{{ .Values.data.pKCGrantType }}"
  partition.keycloak.user: "{{ .Values.data.pKCUser }}"
  partition.keycloak.password: "{{ .Values.data.pKCPassword }}"
  partition.keycloak.realm: "{{ .Values.data.pKCRealm }}"
  partition.keycloak.accept_http: "{{ .Values.data.pKAcceptHttp }}"
  tenantCache.exp.time.in.second: "{{ .Values.data.tenantCacheExpiryInSec }}"
  #SPRING_PROFILES_ACTIVE: "{{ .Values.data.springProfilesActive }}"

  #AMQ
  amqphub.amqp10jms.password: "{{ .Values.data.amqpPassword }}"
  amqphub.amqp10jms.username: "{{ .Values.data.amqpUserName }}"
  amqphub.amqp10jms.remote-url: "{{ .Values.data.amqpURL }}"
  #minio
  ibm.cos.endpoint_url: "http://{{ .Release.Name }}-minio:9000"
  #accesskey and secretkey of minio - refer deployment yaml
  ibm.cos.access_key: "{{ .Values.data.accessKey }}"
  ibm.cos.secret_key: "{{ .Values.data.secretKey }}"
  IBM_COS_REGION: us-east-1
  #policy
  POLICY_API: "http://{{ .Release.Name }}-ibm-policy-deploy:8080/api/policy/v1"
  service.policy.enabled: "{{ .Values.data.policyEnabled }}"
  #crs frame of ref
  osdu.spring.config.createCrsJWTToken: "{{ .Values.data.createCrsJWTTokenEnabled }}"
  CRS_API: "http://{{ .Release.Name }}-ibm-crs-conversion-deploy:8080/api/crs/converter/v2"