{{ if not .Values.data.redisStorageHost }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "redis-%s" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "redis-%s" .Values.conf.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ printf "redis-%s" .Values.conf.appName | quote }}
      annotations:
        sidecar.istio.io/proxyCPU: 30m
    spec:
      containers:
      - args:
        - --requirepass
        - $(REDIS_PASSWORD)
        envFrom:
        - secretRef:
            name: {{ .Values.conf.storageRedisSecretName | quote }}
        image: {{ .Values.data.redisImage | quote }}
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
        name: {{ printf "redis-%s" .Values.conf.appName | quote }}
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          requests:
            memory: 100Mi
{{ end }}
