{{ if not .Values.data.redisStorageHost }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "redis-%s" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: {{ .Values.data.redisStoragePort }}
    protocol: TCP
    targetPort: 6379
  selector:
    app: {{ printf "redis-%s" .Values.conf.appName | quote }}
{{ end }}
