---
# Source: /devops/azure/chart/templates/virtual-service.yaml
{{- if .Values.istioDnsHost }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: osdu
spec:
  hosts:
  - "{{ .Values.istioDnsHost }}"
  gateways:
  - istio-gateway
  http:
  - name: "Settings for /query/records:batch"
    match:
    - uri:
        prefix: "/api/{{ .Chart.Name }}/v2/query/records:batch"
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: 80
    corsPolicy:
      maxAge: "60m"
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Data-Partition-Id
      - Correlation-Id
      - Content-Type
      - Frame-Of-Reference
      allowMethods:
      - POST
      allowOrigins:
      - prefix: "*"
  - name: "Generic Settings"
    match:
    - uri:
        prefix: "/api/{{ .Chart.Name }}/v2"
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: 80
    corsPolicy:
      maxAge: "60m"
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Data-Partition-Id
      - Correlation-Id
      - Content-Type
      allowMethods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      allowOrigins:
      - prefix: "*"
{{- end }}