# Default values for storage-configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  # common
  logLevel: "INFO"
  springProfilesActive: "gcp"
  defaultDataCountry: "US"
  storageServiceAccountEmail: "storage@service.local"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  crsConverterHost: "http://crs-conversion"
  legalHost: "http://legal"
  redisGroupHost: "redis-group-master"
  redisStorageHost: "redis-storage-master"
  
  # gcp
  googleAudiences: ""
conf:
  appName: "storage"
  configmap: "storage-config"
  onPremEnabled: false
