variables:
  GC_SERVICE: storage
  GC_VENDOR: gc
  NO_DATA_ACCESS_TESTER: $GC_NO_DATA_ACCESS_TESTER
  OPA_INTEGRATION_ENABLED: "true"

.define_DATA_BRANCH:
  script:
    - >
      if [[ -z $CI_COMMIT_TAG ]] && [[ $CI_COMMIT_BRANCH =~ ^release\/[0-9]{1,2}.[0-9]{1,2}$ ]];
      then
        REF_DATA_BRANCH=$CI_COMMIT_BRANCH
      elif [[ $CI_COMMIT_TAG =~ ^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$ ]];
      then
        TAG=$(echo $CI_COMMIT_TAG | sed "s/^v//");
        REF_DATA_BRANCH="release/${TAG%.*}";
      else
        REF_DATA_BRANCH="master";
      fi;

gc-anthos-test:
  variables:
    GC_VENDOR: anthos
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_ID: storage-no-access-tester
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET: $OSDU_ANTHOS_STORAGE_NO_ACCESS_CLIENT_SECRET

gc-containerize-bootstrap-gitlab:
  variables:
    GC_ENABLE_BOOTSTRAP: "true"
    BUILD_ARGS: "--build-arg DATA_BRANCH=$REF_DATA_BRANCH"
  before_script:
    - !reference [.define_DATA_BRANCH, script]

gc-containerize-bootstrap-gcr:
  variables:
    GC_ENABLE_BOOTSTRAP: "true"
    BUILD_ARGS: "--build-arg DATA_BRANCH=$REF_DATA_BRANCH"
  before_script:
    - !reference [.define_DATA_BRANCH, script]
