variables:
  GC_SERVICE: storage
  GC_VENDOR: gc
  NO_DATA_ACCESS_TESTER: $GC_NO_DATA_ACCESS_TESTER
  OPA_INTEGRATION_ENABLED: "true"

gc-baremetal-test:
  variables:
    GC_VENDOR: baremetal
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_ID: storage-no-access-tester
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET: $OSDU_BAREMETAL_STORAGE_NO_ACCESS_CLIENT_SECRET

gc-dev2-test:
  variables:
    DATA_ROOT_TESTER: $GC_DEV2_DATA_ROOT_CLIENT_ID
