variables:
  GC_SERVICE: storage
  GC_VENDOR: gc
  NO_DATA_ACCESS_TESTER: $GC_NO_DATA_ACCESS_TESTER_FILE
  OPA_INTEGRATION_ENABLED: "true"

gc-dev2-test:
  variables:
    DATA_ROOT_TESTER: $GC_DEV2_DATA_ROOT_CLIENT_ID_FILE


gc-test:
  variables:
    OPA_INTEGRATION_ENABLED: "true"
