#!/usr/bin/env bash
#
# Reads the sync state for this cycle. A tracking issue's hidden marker is
# authoritative while the issue is open, so an open cycle keeps driving branch
# updates. Without an issue the durable repository variable is read instead,
# which is what stops a filtered no-op SHA from being regenerated (ADR-024).
# That value carries the generation revision that produced it, so a filter
# config or engine change invalidates it instead of pinning a stale tree.
#
# Env: GITHUB_TOKEN, SYNC_MODE (passed through to generation-rev.sh)
# Local: ./check-stored-state.sh <existing_issue_number>

set -euo pipefail

STATE_VARIABLE="SYNC_LAST_EVALUATED_SHA"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -ne 1 ]]; then
  echo "Error: Missing required argument" >&2
  echo "Usage: $0 <existing_issue_number>" >&2
  exit 1
fi

EXISTING_ISSUE_NUMBER="$1"

echo "Reading sync state from existing issue description..."

if [[ -n "$EXISTING_ISSUE_NUMBER" ]]; then
  echo "Found existing issue #$EXISTING_ISSUE_NUMBER, parsing state from description..."

  ISSUE_BODY=$(gh issue view "$EXISTING_ISSUE_NUMBER" --json body --jq '.body')

  LAST_UPSTREAM_SHA=$(awk '
    /<!-- upstream-sha: [0-9a-f]+ -->/ {
      sha = $0
      sub(/^.*<!-- upstream-sha: /, "", sha)
      sub(/ -->.*$/, "", sha)
      if (length(sha) == 40 && sha ~ /^[0-9a-f]+$/) {
        print sha
        exit
      }
    }
  ' <<< "$ISSUE_BODY")

  LAST_SYNC_TIMESTAMP=$(gh issue view "$EXISTING_ISSUE_NUMBER" --json updatedAt --jq '.updatedAt')

  echo "Parsed from issue:"
  echo "  Last upstream SHA: $LAST_UPSTREAM_SHA"
  echo "  Issue number: $EXISTING_ISSUE_NUMBER"
  echo "  Last sync: $LAST_SYNC_TIMESTAMP"
else
  echo "No existing sync issue found, reading durable evaluated-SHA state..."

  # Only "variable not set" may degrade to empty. An auth, rate-limit, or
  # transient failure must not read as first-sync state and silently disable
  # this path, so it fails the run like every other state read.
  READ_ERROR="$(mktemp)"
  if STORED_STATE=$(gh api "repos/${GH_REPO:-${GITHUB_REPOSITORY:-}}/actions/variables/$STATE_VARIABLE" \
    --jq '.value' 2>"$READ_ERROR"); then
    :
  elif grep -qi "HTTP 404" "$READ_ERROR"; then
    STORED_STATE=""
  else
    echo "Error: could not read $STATE_VARIABLE" >&2
    cat "$READ_ERROR" >&2
    rm -f "$READ_ERROR"
    exit 1
  fi
  rm -f "$READ_ERROR"

  STORED_SHA="${STORED_STATE%%:*}"
  STORED_REV="${STORED_STATE#*:}"
  CURRENT_REV="$("$HERE/generation-rev.sh")"

  if [[ ! "$STORED_SHA" =~ ^[0-9a-f]{40}$ ]]; then
    LAST_UPSTREAM_SHA=""
    echo "  No durable state recorded, treating as first sync"
  elif [[ "$STORED_REV" != "$CURRENT_REV" ]]; then
    LAST_UPSTREAM_SHA=""
    echo "  Durable state was generated by $STORED_REV, now $CURRENT_REV - re-evaluating"
  else
    LAST_UPSTREAM_SHA="$STORED_SHA"
    echo "  Last evaluated upstream SHA: $LAST_UPSTREAM_SHA ($CURRENT_REV)"
  fi

  LAST_SYNC_TIMESTAMP=""
fi

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "last_upstream_sha=$LAST_UPSTREAM_SHA"
    echo "current_issue_number=$EXISTING_ISSUE_NUMBER"
    echo "last_sync_timestamp=$LAST_SYNC_TIMESTAMP"
  } >> "$GITHUB_OUTPUT"
fi

# A consumer that stops reading after the first line must not fail the run, so
# SIGPIPE is ignored here; nothing is spawned afterwards to inherit it.
trap '' PIPE
{
  echo "last_upstream_sha=$LAST_UPSTREAM_SHA"
  echo "current_issue_number=$EXISTING_ISSUE_NUMBER"
  echo "last_sync_timestamp=$LAST_SYNC_TIMESTAMP"
} 2>/dev/null || true